### ISSUE TITLE
flutter pub run build_runner build problem

### ISSUE THREAD

**Issue by jamolina2021** [google/json_serializable.dart#1095]
Hi all,

Currently I have a problem and the only solution is to put generate: false (pubspec.yaml)
```
flutter pub run build_runner build
Unhandled exception:
Bad state: Unable to generate package graph, no `C:\FlutterPruebas\electroapp\.dart_tool\flutter_gen\pubspec.yaml` found.
#0      _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:232:5)
#1      _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:206:21)
#2      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:101:33)
<asynchronous suspension>
#3      main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-2.1.7/bin/build_runner.dart:27:30)
<asynchronous suspension>
pub finished with exit code 255
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [VersiÃ³n 10.0.19043.1466], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

Is there any correct solution to solve this problem without having to put generate: false? 

Thanks for your help.

Regards,
Jose

**Comment by kevmoo** [comment]
We'd need @jakemac53 or @natebosch to take a look. This seems like an issue with the build system – or a user error, perhaps.
