### ISSUE TITLE
Decimal is incorrectly serialized

### ISSUE THREAD

**Issue by eximius313** [google/json_serializable.dart#1189]
`flutter --version`
is:
```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (3 months ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

`json_serializable` version is `^6.3.1`

Having such code:
```
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';

part 'json_serialize_bug.g.dart';

void main() {
  var testSerialize = TestSerialize(myDecimal: Decimal.parse("1234.5678"));
  TestSerialize.fromJson(testSerialize.toJson());
}

@JsonSerializable()
class TestSerialize {
  final Decimal myDecimal;
  TestSerialize({
    required this.myDecimal,
  });

  factory TestSerialize.fromJson(Map<String, dynamic> json) => _$TestSerializeFromJson(json);

  Map<String, dynamic> toJson() => _$TestSerializeToJson(this);
}
```

throws:
```
Unhandled exception:
type 'Decimal' is not a subtype of type 'String' in type cast
#0      _$TestSerializeFromJson (package:test/json_serialize_bug.g.dart:11:53)
#1      new TestSerialize.fromJson (package:test/json_serialize_bug.dart:18:64)
#2      main (package:test/json_serialize_bug.dart:8:17)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Because generated code:
```
TestSerialize _$TestSerializeFromJson(Map<String, dynamic> json) =>
    TestSerialize(
      myDecimal: Decimal.fromJson(json['myDecimal'] as String),
    );

Map<String, dynamic> _$TestSerializeToJson(TestSerialize instance) =>
    <String, dynamic>{
      'myDecimal': instance.myDecimal,
    };
```

correctly uses `Decimal.fromJson` for deserialize, bud **does not** uses `myDecimal.toJson()` for serialize (Decimal supports both methods)

**Comment by kevmoo** [comment]
We'd need to see how `Decimal` is implemented. What type is the param of `fromJson`? What's the return type of `Decimal` `toJson`?

**Comment by eximius313** [comment]
```
class Decimal implements Comparable<Decimal> {

[....]

  /// Create a new [Decimal] from its [String] representation.
  factory Decimal.fromJson(String value) => Decimal.parse(value);

[.....]

 /// Returns a [String] representation of `this`.
  @override
  String toString() {
    if (_rational.isInteger) return _rational.toString();
    var value = toStringAsFixed(scale);
    while (
        value.contains('.') && (value.endsWith('0') || value.endsWith('.'))) {
      value = value.substring(0, value.length - 1);
    }
    return value;
  }

  /// Converts `this` to [String] by using [toString].
  String toJson() => toString();
}
```

**Comment by kevmoo** [comment]
Oh! You're not round tripping it through `jsonEncode`. Try setting https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html to `true`

**Comment by eximius313** [comment]
so why `Decimal.fromJson` is being used? Shouldn't it be symmetric?
