### ISSUE TITLE
Stuck on HeartBeat - Waiting on

### ISSUE THREAD

**Issue by dolanmiu** [google/json_serializable.dart#735]
Flutter version:

```
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (6 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

Dart Version:

```
Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "windows_x64"
```

Im using `json_serializable: 3.5.0`

It gets stuck on `flutter pub run build_runner watch --verbose` for over 2+ hours with the output:

```
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[WARNING] Heartbeat:
No actions completed for 15.0s, waiting on:
  - json_serializable:json_serializable on lib/app/auth/email_and_password_entry.dart
  - json_serializable:json_serializable on lib/app/auth/login_page.dart
  - json_serializable:json_serializable on lib/app/auth/register/register_page.dart
  - json_serializable:json_serializable on lib/app/farm_initializer/create_farm/create_farm_page.dart
  - json_serializable:json_serializable on lib/app/farm_initializer/farm_initializer.dart
  .. and 11 more

[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 41m elapsed, 1/17 actions completed.
[WARNING] Heartbeat:
No actions completed for 15.1s, waiting on:
  - json_serializable:json_serializable on lib/app/auth/email_and_password_entry.dart
  - json_serializable:json_serializable on lib/app/auth/login_page.dart
  - json_serializable:json_serializable on lib/app/auth/register/register_page.dart
  - json_serializable:json_serializable on lib/app/farm_initializer/create_farm/create_farm_page.dart
  - json_serializable:json_serializable on lib/app/farm_initializer/farm_initializer.dart
  .. and 11 more

[INFO] Heartbeat:2h 42m elapsed, 1/17 actions completed.
[INFO] Heartbeat:2h 42m elapsed, 1/17 actions completed.
```

**Comment by kevmoo** [comment]
This seems like a bug.

Have you tried `flutter pub run build_runner clean`?

Have you tried updating your dependencies?

**Comment by peterlpt** [comment]
i got the same issue.

in my case, i see a warning msg:

```shell 
$ flutter packages pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 441ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 11.7s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 689ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[WARNING] json_serializable:json_serializable on test/widget_test.dart:
Your current `analyzer` version may not fully support your current SDK version.

Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.

Analyzer language version: 2.9.0
SDK language version: 2.11.0

If you are getting this message and have the latest analyzer please file
an issue at https://github.com/dart-lang/sdk/issues/new with the title
"No published analyzer available for language version 2.11.0".
Please search the issue tracker first and thumbs up and/or subscribe to
existing issues if present to avoid duplicates.
```
note:

```
Your current `analyzer` version may not fully support your current SDK version.
Please try upgrading to the latest `analyzer` by running `flutter packages upgrade`.
```

so, follow the guide, run `flutter packages upgrade`, then work fine.

**Comment by dolanmiu** [comment]
Running `flutter pub run build_runner clean --verbose` doesn't work

I also tried `flutter packages upgrade` and re-running the command, still doesn't work

```
C:\Users\Dolan\Documents\harbinger>flutter packages upgrade
Running "flutter pub upgrade" in harbinger...                       4.3s

C:\Users\Dolan\Documents\harbinger> flutter pub run build_runner clean --verbose
[ +135 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 84f3d28555368a70270e9ac8390a9441df95e752
[        ] executing: [C:\flutter/] git tag --points-at HEAD
[  +62 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.2
[   +7 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +26 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +31 ms] Using C:\flutter\.pub-cache for the pub cache.
[   +3 ms] executing: C:\flutter\bin\cache\dart-sdk\bin\pub.bat run build_runner clean --verbose
Could not find an option named "verbose".

Usage: build_runner clean [arguments]
-h, --help    Print this usage information.

Run "build_runner help" to see global options.
[+18526 ms] "flutter run" took 18,593ms.
[   +5 ms] pub finished with exit code 64
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:375:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:260:15)
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #4      _rootRunUnary (dart:async/zone.dart:1198:47)
           #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #11     _rootRun (dart:async/zone.dart:1190:13)
           #12     _CustomZone.run (dart:async/zone.dart:1093:19)
           #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +133 ms] ensureAnalyticsSent: 131ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 64
```

**Comment by oncul** [comment]
I have same problem

**Comment by kevmoo** [comment]
@jakemac53 @natebosch ?

**Comment by jakemac53** [comment]
The `clean` command doesn't support `--verbose`, try just `flutter pub run build_runner clean`.

What version of analyzer are you on? Can you give us the full log output if you still have issues?

**Comment by pradyumna67** [comment]
Try to upgrade the build_runner version.

**Comment by oncul** [comment]
I solved with this,

Change flutter channel to dev
```
flutter channel dev 
flutter upgrade
flutter pub get
```

My pubspec.yaml

```
environment:
  sdk: ">=2.7.0 <3.0.0"
...

dev_dependencies:
  build_runner: ^1.10.2
  json_serializable: ^3.5.0
```

**Comment by karthikapb89** [comment]
I am still getting the issue

**Comment by kevmoo** [comment]
@karthikapb89 – which version of Dart/Flutter are you on?

**Comment by karthikapb89** [comment]
@kevmoo Flutter 1.22.0 channel stable
Dart 2.10.0

**Comment by kevmoo** [comment]
Please reproduce w/ the latest SDK and the latest version of the package.
