### ISSUE TITLE
why json_serializable can accept non-nullable variables ?

### ISSUE THREAD

**Issue by tbm98** [google/json_serializable.dart#893]
I mean, JSON is a Map and it may null or empty anytime.
what happens if I parse non-nullable variables from the empty map?

**Comment by tbm98** [comment]
cc @kevmoo

**Comment by kevmoo** [comment]
Please provide an example of your Dart code and JSON input/output

**Comment by tbm98** [comment]
task_model.dart
```
import 'package:daily_task/src/config/constants.dart';

/// Created by minh.tran on 14/05/2021.

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:intl/intl.dart';

part 'task_model.freezed.dart';

part 'task_model.g.dart';

@freezed
class TaskModel with _$TaskModel {
  const TaskModel._();

  @JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
  const factory TaskModel(
    String content,
    bool isDone, {
    @_TimeOfDayConverter() TimeOfDay? time,
  }) = _TaskModel;

  factory TaskModel.fromJson(Map<String, dynamic> json) =>
      _$TaskModelFromJson(json);
}

class _TimeOfDayConverter implements JsonConverter<TimeOfDay?, String> {
  const _TimeOfDayConverter();

  @override
  TimeOfDay? fromJson(String json) {
    return null;
    final dateFormater = DateFormat(dateFormat);
    return TimeOfDay.fromDateTime(dateFormater.parse(json));
  }

  @override
  String toJson(TimeOfDay? object) {
    if (object == null) {
      return '';
    }
    return '${object.hour.toString().padLeft(2)}.${object.minute.toString().padLeft(2)}';
  }
}

```

task_model.freezed.dart
```
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides

part of 'task_model.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more informations: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

TaskModel _$TaskModelFromJson(Map<String, dynamic> json) {
  return _TaskModel.fromJson(json);
}

/// @nodoc
class _$TaskModelTearOff {
  const _$TaskModelTearOff();

  _TaskModel call(String content, bool isDone,
      {@_TimeOfDayConverter() TimeOfDay? time}) {
    return _TaskModel(
      content,
      isDone,
      time: time,
    );
  }

  TaskModel fromJson(Map<String, Object> json) {
    return TaskModel.fromJson(json);
  }
}

/// @nodoc
const $TaskModel = _$TaskModelTearOff();

/// @nodoc
mixin _$TaskModel {
  String get content => throw _privateConstructorUsedError;
  bool get isDone => throw _privateConstructorUsedError;
  @_TimeOfDayConverter()
  TimeOfDay? get time => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $TaskModelCopyWith<TaskModel> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $TaskModelCopyWith<$Res> {
  factory $TaskModelCopyWith(TaskModel value, $Res Function(TaskModel) then) =
      _$TaskModelCopyWithImpl<$Res>;
  $Res call(
      {String content, bool isDone, @_TimeOfDayConverter() TimeOfDay? time});
}

/// @nodoc
class _$TaskModelCopyWithImpl<$Res> implements $TaskModelCopyWith<$Res> {
  _$TaskModelCopyWithImpl(this._value, this._then);

  final TaskModel _value;
  // ignore: unused_field
  final $Res Function(TaskModel) _then;

  @override
  $Res call({
    Object? content = freezed,
    Object? isDone = freezed,
    Object? time = freezed,
  }) {
    return _then(_value.copyWith(
      content: content == freezed
          ? _value.content
          : content // ignore: cast_nullable_to_non_nullable
              as String,
      isDone: isDone == freezed
          ? _value.isDone
          : isDone // ignore: cast_nullable_to_non_nullable
              as bool,
      time: time == freezed
          ? _value.time
          : time // ignore: cast_nullable_to_non_nullable
              as TimeOfDay?,
    ));
  }
}

/// @nodoc
abstract class _$TaskModelCopyWith<$Res> implements $TaskModelCopyWith<$Res> {
  factory _$TaskModelCopyWith(
          _TaskModel value, $Res Function(_TaskModel) then) =
      __$TaskModelCopyWithImpl<$Res>;
  @override
  $Res call(
      {String content, bool isDone, @_TimeOfDayConverter() TimeOfDay? time});
}

/// @nodoc
class __$TaskModelCopyWithImpl<$Res> extends _$TaskModelCopyWithImpl<$Res>
    implements _$TaskModelCopyWith<$Res> {
  __$TaskModelCopyWithImpl(_TaskModel _value, $Res Function(_TaskModel) _then)
      : super(_value, (v) => _then(v as _TaskModel));

  @override
  _TaskModel get _value => super._value as _TaskModel;

  @override
  $Res call({
    Object? content = freezed,
    Object? isDone = freezed,
    Object? time = freezed,
  }) {
    return _then(_TaskModel(
      content == freezed
          ? _value.content
          : content // ignore: cast_nullable_to_non_nullable
              as String,
      isDone == freezed
          ? _value.isDone
          : isDone // ignore: cast_nullable_to_non_nullable
              as bool,
      time: time == freezed
          ? _value.time
          : time // ignore: cast_nullable_to_non_nullable
              as TimeOfDay?,
    ));
  }
}

/// @nodoc

@JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
class _$_TaskModel extends _TaskModel with DiagnosticableTreeMixin {
  const _$_TaskModel(this.content, this.isDone,
      {@_TimeOfDayConverter() this.time})
      : super._();

  factory _$_TaskModel.fromJson(Map<String, dynamic> json) =>
      _$_$_TaskModelFromJson(json);

  @override
  final String content;
  @override
  final bool isDone;
  @override
  @_TimeOfDayConverter()
  final TimeOfDay? time;

  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return 'TaskModel(content: $content, isDone: $isDone, time: $time)';
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties
      ..add(DiagnosticsProperty('type', 'TaskModel'))
      ..add(DiagnosticsProperty('content', content))
      ..add(DiagnosticsProperty('isDone', isDone))
      ..add(DiagnosticsProperty('time', time));
  }

  @override
  bool operator ==(dynamic other) {
    return identical(this, other) ||
        (other is _TaskModel &&
            (identical(other.content, content) ||
                const DeepCollectionEquality()
                    .equals(other.content, content)) &&
            (identical(other.isDone, isDone) ||
                const DeepCollectionEquality().equals(other.isDone, isDone)) &&
            (identical(other.time, time) ||
                const DeepCollectionEquality().equals(other.time, time)));
  }

  @override
  int get hashCode =>
      runtimeType.hashCode ^
      const DeepCollectionEquality().hash(content) ^
      const DeepCollectionEquality().hash(isDone) ^
      const DeepCollectionEquality().hash(time);

  @JsonKey(ignore: true)
  @override
  _$TaskModelCopyWith<_TaskModel> get copyWith =>
      __$TaskModelCopyWithImpl<_TaskModel>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$_$_TaskModelToJson(this);
  }
}

abstract class _TaskModel extends TaskModel {
  const factory _TaskModel(String content, bool isDone,
      {@_TimeOfDayConverter() TimeOfDay? time}) = _$_TaskModel;
  const _TaskModel._() : super._();

  factory _TaskModel.fromJson(Map<String, dynamic> json) =
      _$_TaskModel.fromJson;

  @override
  String get content => throw _privateConstructorUsedError;
  @override
  bool get isDone => throw _privateConstructorUsedError;
  @override
  @_TimeOfDayConverter()
  TimeOfDay? get time => throw _privateConstructorUsedError;
  @override
  @JsonKey(ignore: true)
  _$TaskModelCopyWith<_TaskModel> get copyWith =>
      throw _privateConstructorUsedError;
}
```

task_model.g.dart
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'task_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TaskModel _$_$_TaskModelFromJson(Map<String, dynamic> json) {
  return _$_TaskModel(
    json['content'] as String,
    json['is_done'] as bool,
    time: const _TimeOfDayConverter().fromJson(json['time'] as String),
  );
}

Map<String, dynamic> _$_$_TaskModelToJson(_$_TaskModel instance) =>
    <String, dynamic>{
      'content': instance.content,
      'is_done': instance.isDone,
      'time': const _TimeOfDayConverter().toJson(instance.time),
    };
```

execute
```
final task = TaskModel.fromJson(jsonDecode('{}'));

    print(task.time.toString());
    print(task.content.toString());
    print(task.isDone.toString());
```

error
```
Performing hot restart...
Syncing files to device sdk gphone x86...
Restarted application in 1,317ms.

======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
type 'Null' is not a subtype of type 'String' in type cast

When the exception was thrown, this was the stack: 
#0      _$_$_TaskModelFromJson (package:daily_task/src/models/task_model.g.dart:11:21)
#1      new _$_TaskModel.fromJson (package:daily_task/src/models/task_model.freezed.dart:143:7)
#2      _$TaskModelFromJson (package:daily_task/src/models/task_model.freezed.dart:16:21)
#3      new TaskModel.fromJson (package:daily_task/src/models/task_model.dart:27:7)
#4      _MyHomePageState._incrementCounter (package:daily_task/src/screens/home/home_page.dart:22:28)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#9f01c
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(354.2, 466.5)
  finalLocalPosition: Offset(33.4, 28.3)
  button: 1
  sent tap down
====================================================================================================

======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
type 'Null' is not a subtype of type 'String' in type cast

When the exception was thrown, this was the stack: 
#0      _$_$_TaskModelFromJson (package:daily_task/src/models/task_model.g.dart:11:21)
#1      new _$_TaskModel.fromJson (package:daily_task/src/models/task_model.freezed.dart:143:7)
#2      _$TaskModelFromJson (package:daily_task/src/models/task_model.freezed.dart:16:21)
#3      new TaskModel.fromJson (package:daily_task/src/models/task_model.dart:27:7)
#4      _MyHomePageState._incrementCounter (package:daily_task/src/screens/home/home_page.dart:22:28)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#9f01c
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(354.2, 466.5)
  finalLocalPosition: Offset(33.4, 28.3)
  button: 1
  sent tap down
====================================================================================================
```

and another issue is analyze not warning when I call `task.time.toString()` instead of `task.time?.toString()`

**Comment by tbm98** [comment]
Hi @kevmoo. Are you following this issue?
tag `State: needs info` should be removed

**Comment by kevmoo** [comment]
![image](https://user-images.githubusercontent.com/17034/120403268-b50ae480-c2f8-11eb-9648-4c8416252158.png)

`content` is not a nullable String. So this fails. You need to change the type to `String?` if you want to accept null values!
