### ISSUE TITLE
The class has no default constructor error when generating with enum

### ISSUE THREAD

**Issue by UnicornsOnLSD** [google/json_serializable.dart#911]
# Version
```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (9 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```
When running `flutter pub run build_runner build`, the build fails on my enum. The enum is:
```dart
@JsonSerializable(explicitToJson: true)
enum SyncPlayUserAccessType {
  CreateAndJoinGroups,
  JoinGroups,
  None,
}
```
and the output of `flutter pub run build_runner build` is:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 262ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 53ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 374ms

[INFO] Running build...
[INFO] Running build completed, took 17ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 31ms

[SEVERE] json_serializable:json_serializable on lib/models/JellyfinModels.dart (cached):

The class `SyncPlayUserAccessType` has no default constructor.
package:finamp/models/JellyfinModels.dart:3008:6
     ╷
3008 │ enum SyncPlayUserAccessType {
     │      ^^^^^^^^^^^^^^^^^^^^^^
     ╵
[SEVERE] Failed after 57ms
pub finished with exit code 1
```

Here is `flutter pub run build_runner build --delete-conflicting-outputs -vv`:

```
[  +39 ms] executing: uname -m
[  +18 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +4 ms] executing: [/home/james/Development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] executing: [/home/james/Development/flutter/] git tag --points-at
02c026b03cd31dd3f867e5faeb7e104cce174c5f
[   +7 ms] Exit code 0 from: git tag --points-at 02c026b03cd31dd3f867e5faeb7e104cce174c5f
[        ] 2.2.1
[   +4 ms] executing: [/home/james/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/james/Development/flutter/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +45 ms] executing: [/home/james/Development/flutter/] git rev-parse --abbrev-ref HEAD
[   +2 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +23 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[   +7 ms] executing: /home/james/Development/flutter/bin/cache/dart-sdk/bin/pub run build_runner build
--delete-conflicting-outputs -vv
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 277ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 52ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 384ms

[INFO] Build:Running build...
[INFO] Heartbeat:1.0s elapsed, 0/4 actions completed.
[INFO] Heartbeat:2.3s elapsed, 0/4 actions completed.
[FINE] chopper_generator:chopper_generator on lib/models/JellyfinModels.dart:Running ChopperGenerator
[FINE] chopper_generator:chopper_generator on lib/models/FinampModels.dart:Running ChopperGenerator
[INFO] Heartbeat:6.4s elapsed, 2/4 actions completed.
[FINE] chopper_generator:chopper_generator on lib/services/JellyfinApi.dart:Running ChopperGenerator
[FINE] chopper_generator:chopper_generator on lib/services/DownloadsHelper.dart:Running ChopperGenerator
[FINE] hive_generator:hive_generator on lib/models/JellyfinModels.dart:Running TypeAdapterGenerator
[FINE] hive_generator:hive_generator on lib/models/FinampModels.dart:Running TypeAdapterGenerator
[FINE] hive_generator:hive_generator on lib/services/JellyfinApi.dart:Running TypeAdapterGenerator
[FINE] hive_generator:hive_generator on lib/services/DownloadsHelper.dart:Running TypeAdapterGenerator
[FINE] json_serializable:json_serializable on lib/services/JellyfinApi.dart:Running JsonSerializableGenerator - 1 of 2
[FINE] json_serializable:json_serializable on lib/services/JellyfinApi.dart:Running JsonLiteralGenerator - 2 of 2
[FINE] json_serializable:json_serializable on lib/services/DownloadsHelper.dart:Running JsonSerializableGenerator - 1 of 2
[FINE] json_serializable:json_serializable on lib/services/DownloadsHelper.dart:Running JsonLiteralGenerator - 2 of 2
[FINE] json_serializable:json_serializable on lib/models/JellyfinModels.dart:Running JsonSerializableGenerator - 1 of 2
[SEVERE] json_serializable:json_serializable on lib/models/JellyfinModels.dart:

The class `SyncPlayUserAccessType` has no default constructor.
package:finamp/models/JellyfinModels.dart:3008:6
     ╷
3008 │ enum SyncPlayUserAccessType {
     │      ^^^^^^^^^^^^^^^^^^^^^^
     ╵
package:json_serializable/src/decode_helper.dart 247:5     _writeConstructorInvocation
package:json_serializable/src/decode_helper.dart 56:18     DecodeHelper.createFactory
package:json_serializable/src/generator_helper.dart 85:28  GeneratorHelper.generate

[FINE] json_serializable:json_serializable on lib/models/FinampModels.dart:Running JsonSerializableGenerator - 1 of 2
[FINE] json_serializable:json_serializable on lib/models/FinampModels.dart:Running JsonLiteralGenerator - 2 of 2
[INFO] Build:Running build completed, took 7.1s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 28ms

[SEVERE] Build:
Failed after 7.2s
[+9033 ms] "flutter run" took 9,074ms.
[   +3 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:366:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

I am using json_annotation 4.0.1, json_serializable 4.1.3, and build_runner 2.0.4.

**Comment by kevmoo** [comment]
You cannot annotate an enough. Sorry.

It'll be more clear when https://github.com/google/json_serializable.dart/pull/912 lands
